### PR TITLE
rearranging all of the sql queries and dependencies for the reporting…

### PR DESCRIPTION
**Pull request by bethanne-card**
… database

### CODE REVIEW

**Comment by bethanne-card** [comment]
@sarvothaman I tried to modularize the reporting database scripts a bit more but putting all of the indexes statements in the same file as the table creation. I also broke up the 04_support and 06_reporting_db into more scripts so that if I need to go back and fix all of the cpc or all of the location, they will be easier to find. Let me know if you see any issues with this logic.

**Review by sarvothaman — CHANGES_REQUESTED** [review]
I don't have any objections to breaking up bigger steps into smaller. That will only help. l'l recommend not merging this change though, until running a full trial run. The ordering of things (particularly when indices are involved) can significantly affect run time of queries. Some queries may never complete if the indices are created out of order.  insert statement after adding index on target table slows down insert process but not having index on source table before load will slow down the select statement.etc  I don't see any such examples in the changes with this PR, but recommend creating another dummy reporting database anyway.

**Comment by bethanne-card** [comment]
Thank you for your feedback @sarvothaman. I'll build a test reporting DB using this branch and report back.

**Comment by bethanne-card** [comment]
@sarvothaman the reporting DB code successfully ran. I had to make a few tweaks to the codebase due to the changes made here and some changes that would have need to be made either way. Am I okay to merge this code?

**Review by sarvothaman — APPROVED** [review]

**Pull request merged**
